version: 1.0.{build}
branches:
  only:
  - master
max_jobs: 3
image: Visual Studio 2017
configuration: Debug
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_test:
- ps: >-
    x64\Debug\ProjectBarnabusTest.exe --gtest_output=xml:report.xml

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path report.xml))
test:
  assemblies:
    only:
    - x64\Debug\gtest_main.dll
    - x64\Debug\gtest.dll