version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    only:
    - x64\Debug\gtest_main.dll
    - x64\Debug\gtest.dll