version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- x64\Debug\ProjectBarnabusTest.exe