version: 1.0.{build}
branches:
  only:
  - master
max_jobs: 3
image: Visual Studio 2017
configuration: Debug
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv.exe"

    DEVENV% /build "Release" GameExampleInstallation\GameExampleInstallation.vdproj
test:
  assemblies:
    only:
    - x64\Debug\gtest_main.dll
    - x64\Debug\gtest.dll
artifacts:
- path: C:\projects\projectbarnabus\x64\Debug\*
  name: Test