image:
  - Visual Studio 2022

before_build:
- cmd: nuget restore
- ps: Start-FileDownload 'https://vulkan.lunarg.com/sdk/download/1.3.290.0/windows/VulkanSDK-1.3.290.0-Installer.exe?Human=true'
- cmd: VulkanSDK-1.3.290.0-Installer.exe --accept-licenses --default-answer --confirm-command install
- cmd: set VULKAN_SDK=C:\VulkanSDK\1.3.290.0

test:
  assemblies:
    only:
    - assimpd.dll
    - glew32.dll
    - glfw3d.dll

after_build:
- 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\x64\Debug\*

artifacts:
  - path: myapp.zip
    name: MyApp

#test_script:
#- 'x64\Debug\ProjectBarnabusTest.exe --gtest_output=xml:report.xml'

#after_test:
#- ps:
#    $wc = New-Object 'System.Net.WebClient'
#    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\report.xml))
